name: flutter_notes_app
description: A Flutter app for managing notes with Firebase authentication and Firestore integration.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.6.0
  provider: ^6.1.2
  markdown: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - assets/
